# Note: For production. For development, use `docker-compose.yml`
version: '3.0'
services:
  nginx:
    image: fjedi-nginx
    build:
      context: .
    environment:
      DOMAINS: $DOMAINS
      NGX_MAX_WORKER_CONNECTIONS: 512
      NGX_DNS_SERVER: 8.8.8.8
      NGX_PAGESPEED_MODULE_STATUS: "off"
      NGX_GZIP_COMPRESSION_LEVEL: 5
      NGX_BROTLI_COMPRESSION_LEVEL: 5
    container_name: "nginx"
    network_mode: bridge
    expose:
      - 80
      - 443
    ports:
      - 8080:80
      - 8443:443
    restart: unless-stopped
