# docker-compose.yml
version: "3.0"

services:
  nginx:
    image: fjedi-nginx
    build:
      context: .
    environment:
      # DOMAINS: "example1.com|example2.com"
      DOMAINS: $DOMAINS
      # uncomment it only when you check everything with Let's Encrypt staging server (Let's Encrypt prod has weekly limits)
      # SSL_PROD: "yes"
      NGX_MAX_WORKER_CONNECTIONS: 512
      NGX_DNS_SERVER: 8.8.8.8
      NGX_GZIP_COMPRESSION_LEVEL: 5
      NGX_BROTLI_COMPRESSION_LEVEL: 5
    container_name: "nginx"
    network_mode: bridge
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      # don't map particular conf files, supervisor won't restart nginx on change in such files
      # only map directory conf.d, in this case everything works fine
      - type: bind
        source: ./conf
        target: /etc/nginx/conf.d
      # we will store here ssl certificates
      - type: bind
        source: /etc/resty-auto-ssl
        target: /etc/resty-auto-ssl
      # remove it if you don't want to persist logs
      - type: bind
        source: /var/log/nginx
        target: /var/log/nginx
